### ISSUE TITLE
Abrir los casos de uso

### ISSUE THREAD

**Issue by fermaf** [jpherrerap/llm-hackathon-2024#1]
RelaxAgent, tal como @jpherrerap dijo, usó   "Datos Reales anotados por personas". 

He estado trabajando en un proyecto similar pero mis Datos son con  datoa Públicos (que el Estado tiene obligación de entregar), ya tengo un caso de uso, pero mi implementación llega has implementar en  Google Colab... no se como seguir..((soy newbie entusiasta).

**Comment by jpherrerap** [comment]
Hola @fermaf , qué bueno que te haya interesado! Lo que te recomiendo es que migres tu código de colab a un proyecto en Python. Da un poco de miedo jaja pero usa algún framework como FastAPI (mi favorito), Flask o Django y anda probando. 

Por ejemplo, nuestro código está medio desordenado pero puedes mirar cómo movimos lo de [scraper_example.ipynb](https://github.com/jpherrerap/llm-hackathon-2024/blob/master/back/scraper_example.ipynb) a [falabella_scraper.py](https://github.com/jpherrerap/llm-hackathon-2024/blob/master/back/falabella_scraper.py), cuya clase y funciones pueden ser fácilmente movidas a [main.py](https://github.com/jpherrerap/llm-hackathon-2024/blob/master/main.py), el script principal que ejcuta la aplicación.

También puedes ver estos pequeños [ejemplos de LangServe](https://github.com/langchain-ai/langserve/tree/main/examples), un módulo de la librería LangChain que también sirve para crear aplicaciones con agentes de IA.

Mucha suerte :D

**Comment by jpherrerap** [comment]
Después de eso te preocupas del frontend. Otra recomendación es este template de un proyecto full stack hecho con FastAPI que viene con un montón de cosas: https://github.com/fastapi/full-stack-fastapi-template. Lo principal se encuentra en la carpeta [backend/app](https://github.com/fastapi/full-stack-fastapi-template/tree/master/backend/app).
